### ISSUE TITLE
add company_logo in sponsor table

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/api-smesummit.id-2019#13]
We will save public logo url for sponsor

**Comment by mazipan** [comment]
For now, we will save public url.
So, users need to input url image.

**Comment by ammarfaizi2** [comment]
I am still working on it, will send you an update soon.

**Comment by ammarfaizi2** [comment]
Hello,

I have fixed the sponsor registration API and added a new field `company_logo` with URL input format.

Here are the required fields for sponsor registration API:
```json
[
    "company_name",
    "company_logo",
    "company_sector",
    "email_pic",
    "phone",
    "sponsor_type"
]
```

If you have any issue with this API, do not hesitate to contact me.

Thank you for being patient due to the backend misunderstanding related to the sponsor registration API.

**Comment by ammarfaizi2** [comment]
Ref https://github.com/phpid-jakarta/api-smesummit.id-2019/pull/21
